server:
  port: 8888

spring:
  application:
    name: TestApacheCamel

camel:
  springboot:
    main-run-controller: true

broker:
  activemq-first-vendor:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  activemq-second-vendor:
    broker-url: tcp://localhost:61617
    user: admin
    password: admin
  rabbitmq-first-vendor:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: FIRST-VENDOR-EVENTS
  rabbitmq-second-vendor:
    host: localhost
    port: 5673
    username: guest
    password: guest
    virtual-host: SECOND-VENDOR-EVENTS


events:
  insurance:
    multitenant:
      first-vendor:
        exchange-name: EX-FIRST-VENDOR
        queue-name: QU-FIRST-VENDOR

      second-vendor:
        exchange-name: EX-SECOND-VENDOR
        queue-name: QU-SECOND-VENDOR

    splitter:
      dev-events:
        exchange-name: ex-insurance-events-dev
        queue-name: qu-insurance-events-dev
        routing-key: Environment.*
      test-events:
        exchange-name: ex-insurance-events-test
        queue-name: qu-insurance-events-test
        routing-key: Environment.*