server:
  port: 9090

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: INSURANCE-EVENTS

camel:
  spring-rabbitmq:
    auto-declare: false

rife:
  insurance:
    events:
      exchange-name: ex-insurance-events
      routing-key: Mobility.*
      queue-name: qu-insurance-events.mobility
      redelivery-delay: 5000
      max-redeliveries: 2
    dev-events:
      exchange-name: ex-insurance-events-dev
      queue-name: qu-insurance-events-dev.mobility
    rec-events:
      exchange-name: ex-insurance-events-rec
      queue-name: qu-insurance-events-rec.mobility